name: ICTD Lab
url: http://ictd.cs.washington.edu

exclude: [bibble, README.md, Makefile]

# use this library to parse Markdown
#markdown: redcarpet
#redcarpet:
#    extensions: [smart, tables, with_toc_data, strikethrough]

# colorize code snippets with the pygment module
highlighter: rouge

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

navigation:
    - title: Home
      link: /
    - title: Who We Are
      link: /who_we_are.html
    - title: What We Do
      link: /what_we_do.html
    - title: Research Opportunities
      link: /research_opportunities.html
